# See https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: tuesday
    open-pull-requests-limit: 2
    versioning-strategy: increase
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    labels:
      - dependencies
      - javascript
      - skip-changelog
    reviewers:
      - process-analytics/pa-collaborators
    groups:
       css:
          patterns:
            - "autoprefixer"
            - "cssnano"
            - "postcss*"
            - "tailwindcss"
       jest:
          patterns:
            - "@jest/*"
            - "jest"
            - "jest-*"
       lint:
          patterns:
            - "@typescript-eslint/*"
            - "eslint"
            - "eslint-*"
            - "lint-staged"
            - "prettier"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: tuesday
    open-pull-requests-limit: 2
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore(gha)"
    labels:
      - dependencies
      - github_actions
      - skip-changelog
    reviewers:
      - process-analytics/pa-collaborators
