# See https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: tuesday
    open-pull-requests-limit: 2
    versioning-strategy: increase
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    labels:
      - dependencies
      - javascript
      - skip-changelog
    reviewers:
      - process-analytics/pa-collaborators
    ignore:
      # typescript must not be updated in packages/check-ts-support. Its version must remain unchanged to test the minimum version supported by bv-addons
      # For more details, see:
      #    https://github.com/process-analytics/bv-experimental-add-ons/pull/90
      #    https://github.com/process-analytics/bv-experimental-add-ons/pull/92
      - dependency-name: "typescript"
    groups:
       css:
          patterns:
            - "autoprefixer"
            - "cssnano"
            - "postcss*"
            - "tailwindcss"
       lint:
          patterns:
            - "@types/eslint"
            - "@typescript-eslint/*"
            - "eslint"
            - "eslint-*"
            - "lint-staged"
            - "prettier"
       test:
         patterns:
           - "@jest/*"
           - "@testing-library/*"
           - "jest"
           - "jest-*"
           - "ts-jest"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: tuesday
    open-pull-requests-limit: 2
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore(gha)"
    labels:
      - dependencies
      - github_actions
      - skip-changelog
    reviewers:
      - process-analytics/pa-collaborators
