name: 'Build Setup'
description: 'Setup node and install dependencies'
inputs:
  registry-url:
    description: 'Optional registry to set up for auth.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        registry-url: ${{ inputs.registry-url }}
    - name: Install dependencies
      uses: bahmutov/npm-install@v1
      with:
        # restore "--ignore-scripts" when there is no need to patch bpmn-visualization@0.38.1 anymore during post-install (to make jest resolve it)
        install-command: npm ci --prefer-offline --audit false
