name: Build

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - 'packages/addons/src/**/*'
      - 'packages/addons/src/*.json'
      - '.nvmrc'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - 'packages/addons/src/**/*'
      - 'packages/addons/src/*.json'
      - '.nvmrc'
      - 'package.json'
      - 'package-lock.json'

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      # SonarCloud: checks and pull-requests
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Build Setup
        uses: ./.github/actions/build-setup
      - name: Build Library
        run: npm run build -w packages/addons
