name: Build

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/build-setup/**/*'
      - '.github/workflows/build.yml'
      - 'packages/addons/src/**/*'
      - 'packages/addons/test/**/*'
      - 'packages/addons/*.js'
      - 'packages/addons/**/*.json'
      - 'packages/check-ts-support/src/**/*'
      - 'packages/check-ts-support/**/*.json'
      - '.nvmrc'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches:
      - main
    paths:
      - '.github/actions/build-setup/**/*'
      - '.github/workflows/build.yml'
      - 'packages/addons/src/**/*'
      - 'packages/addons/test/**/*'
      - 'packages/addons/*.js'
      - 'packages/addons/**/*.json'
      - 'packages/check-ts-support/src/**/*'
      - 'packages/check-ts-support/**/*.json'
      - '.nvmrc'
      - 'package.json'
      - 'package-lock.json'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Setup
        uses: ./.github/actions/build-setup
      - name: Build Library
        run: npm run build -w packages/addons
      - name: Test
        id: 'test'
        run: npm test -w packages/addons -- --coverage
      - name: Upload coverage report
        if: ${{ steps.test.outcome == 'success' || steps.test.outcome == 'failure' }} # when tests have been run
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{github.sha}}
          path: packages/addons/coverage
      - name: Check TypeScript Support
        run: npm test -w packages/check-ts-support
      - name: Check Lint
        run: npm run lint-check
