name: Build

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - 'packages/addons/src/**/*'
      - 'packages/addons/**/*.json'
      - 'packages/check-ts-support/src/**/*'
      - 'packages/check-ts-support/**/*.json'
      - '.nvmrc'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - 'packages/addons/src/**/*'
      - 'packages/addons/**/*.json'
      - 'packages/check-ts-support/src/**/*'
      - 'packages/check-ts-support/**/*.json'
      - '.nvmrc'
      - 'package.json'
      - 'package-lock.json'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build Setup
        uses: ./.github/actions/build-setup
      - name: Build Library
        run: npm run build -w packages/addons
      - name: Check TypeScript Support
        run: npm test -w packages/check-ts-support
      - name: Test
        run: npm test -w packages/addons
      - name: Check Lint
        run: npm run lint-check
