name: Deploy PR demo

on:
  pull_request:
    # To manage 'surge-preview' action teardown, add default event types + closed event type
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - '.github/actions/build/**/*'
      - '.github/workflows/deploy-pr-demo.yml'
      - 'packages/addons/src/**/*'
      - 'packages/addons/**/*.json'
      - 'packages/demo/src/**/*'
      - 'packages/demo/**/*.json'
      - 'packages/demo/**/*.html'
      - '.nvmrc'
      - 'package.json'
      - 'package-lock.json'

jobs:
  # Keep unique across jobs using surge preview (preview url and PR comment id).
  # Use a short id to avoid reaching the surge subdomain length limit. See https://github.com/bonitasoft/actions/issues/101
  demo:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write # surge-preview: PR comments
    steps:
      - uses: actions/checkout@v3
      - name: Build Setup
        uses: ./.github/actions/build-setup
        if: github.event.action != 'closed'
      - name: Build demo
        if: github.event.action != 'closed'
        run: npm run build -w packages/addons -w packages/demo
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: github.event.action != 'closed'
        with:
          name: demo-pr-${{github.event.pull_request.number}}-${{github.sha}}
          path: packages/demo/dist
      - uses: bonitasoft/actions/packages/surge-preview-tools@v2
        id: surge-preview-tools
        with:
          surge-token: ${{ secrets.SURGE_TOKEN }}
      - name: Manage surge preview
        if: steps.surge-preview-tools.outputs.can-run-surge-command == 'true'
        uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: './packages/demo/dist'
          failOnError: true
          teardown: 'true'
          build: echo 'already built!'
