name: Deploy the demo on GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/build-setup/**/*'
      - '.github/workflows/deploy-demo.yml'
      - 'packages/addons/src/**/*'
      - 'packages/addons/**/*.json'
      - 'packages/demo/src/**/*'
      - 'packages/demo/**/*.json'
      - 'packages/demo/**/*.html'
      - '.nvmrc'
      - 'package.json'
      - 'package-lock.json'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Setup
        uses: ./.github/actions/build-setup
      - name: Build demo
        run: npm run build -w packages/addons -w packages/demo
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./packages/demo/dist

  deploy:
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
